services:
  - type: web
    name: eco-haven-frontend
    runtime: docker
    dockerContext: frontend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eco-haven-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://eco-haven-frontend.onrender.com
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: UPLOADTHING_SECRET
        sync: false
      - key: UPLOADTHING_APP_ID
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false

  - type: web
    name: eco-haven-backend
    runtime: docker
    dockerContext: backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

databases:
  - name: eco-haven-db
    plan: free
    postgresMajorVersion: 16
